<?php

namespace AdminBundle\Repository;

/**
 * ImagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImagesRepository extends \Doctrine\ORM\EntityRepository {

    public function ListeImages() {

        return $this
                ->createQueryBuilder('a')
                ->leftJoin('a.bloc', 'x')
                ->select('a.id , a.description, x.description as descbloc, a.image, a.description as descimage')
                ->getQuery()
                ->getResult()
                ;


        
    }
    
    public function ListeImagesSlider() {

        return $this
                ->createQueryBuilder('a')
                ->leftJoin('a.bloc', 'x')
                ->select('a.id , a.description, x.description as descbloc, a.image, a.description as descimage')
                ->where("x.description Like 'Slider'")
                ->getQuery()
                ->getResult()
                ;


        
    }
    

}
