<?php

namespace AdminBundle\Repository;
use Doctrine\ORM\Query\ResultSetMapping;
/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends \Doctrine\ORM\EntityRepository
{
    public function ListeMenu() {

        return $this
                ->createQueryBuilder('a')
                ->select('a.id , a.description, a.url')
                ->getQuery()
                ->getResult()
                ;


        
    }
    
    
}
