<?php

namespace AdminBundle\Repository;

/**
 * Menu2Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Menu2Repository extends \Doctrine\ORM\EntityRepository
{
     public function ListeMenu() {

        return $this
                ->createQueryBuilder('a')
                ->select('a.id , a.description, a.url')
                ->getQuery()
                ->getResult()
                ;


        
    }
    
}
