<?php

namespace AdminBundle\Repository;
use Doctrine\ORM\Query\ResultSetMapping;

/**
 * ResponsbalesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResponsbalesRepository extends \Doctrine\ORM\EntityRepository
{
    public function ListeResponsables() {

        $conn = $this->getEntityManager()->getConnection();
        $sql = 'SELECT * FROM fos_user';
        $stmt = $conn->prepare($sql);
        $stmt->execute();
        return $stmt->fetchAll();
        
        
        
    }
}
