AdminBundle\Entity\Responsbales:
    type: entity
    table: null
    repositoryClass: AdminBundle\Repository\ResponsbalesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    lifecycleCallbacks: {  }
